###################################################################################
# EKS
###################################################################################

output "cluster_endpoint" {
  description = "Endpoint for EKS control plane."
  value       = module.eks.cluster_endpoint
}

output "kubectl_config" {
  description = "kubectl config as generated by the module."
  value       = module.eks.kubeconfig
}


###################################################################################
# IAM
###################################################################################
output "this_iam_user_name" {
  description = "The user's name"
  value       = module.iam_user.this_iam_user_name
}
