apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
data:
  repositories: |
    - url: https://git.deimos.co.za/mensaah/terraform-trials.git
      passwordSecret:
        name: argocd-repo-credentials
        key: password
      usernameSecret:
        name: argocd-repo-credentials
        key: username
